#!/bin/bash

# common
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# 確認不要のときだけ-fをつける
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias cd.='cd ./'
alias cd..='cd ../'
alias cd...='cd ../../'

# common
alias c='code'
alias e='exit'
alias g='git'
alias md='mkdir -p'
alias mk='make'
alias c.='code .'
# alias src='source ~/.bashrc'
alias unzipj='unzip -O sjis'
alias unsetproxy='unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY'
alias cdots='code ~/.env_global ~/.bash_aliases ~/.gitconfig'

# python
alias python='python3'
alias pip='pip3'
alias pi='pip install'
alias piu='pip install -U'
alias pui='pip uninstall -y'
alias pfg='pip freeze | grep'
alias jn='jupyter notebook'
alias jl='jupyter lab'
alias srun='streamlit run'
# alias mfsv="mlflow server --backend-store-uri sqlite:////home/oga/.mlflow/mlflow.sqlite --default-artifact-root file:/home/oga/.mlflow/mlruns --host localhost --port 5000"
# alias mfrm="rm -r /home/oga/.mlflow; mkdir /home/oga/.mlflow"
# alias mfui="mlflow ui --backend-store-uri ./data/mlruns"
# alias opdb="optuna-dashboard sqlite:///./data/optuna.sqlite --port 5001"

# docker
alias du='docker compose up -d'
alias dd='docker compose down'
alias ddu='dd && du'
# alias dps="docker ps -a && echo '' && docker images -a"
# alias drmi="dd && docker rmi $(docker images -a -q)"
# alias drmiu='drmi && du' これはerrorが起こるので、duまで行かない、修正したい
# docker container prune -f & docker image prune -a -f & docker volume prune -f & docker network prune -f
